services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: nvidia/cuda:11.8.0-base-ubuntu20.04
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
