version: '3.9'
services:
  flask:
    container_name: flask
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    container_name: database
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

#docker-compose up -d database/flask